accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('<int:pk>/profile/',views.UserProfileUpdation.as_view(),name='update_profile'),
    path('<int:pk>/createprofile/',views.NewUserCreation.as_view(),name='create_profile'),
    #path('user_profile_updation/<int:pk>',views.UserProfileUpdation.as_view(),name='update_profile'),
]

blogProject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('',views.HomePage.as_view(),name = 'home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('accouts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('projects/',include('projects.urls',namespace = 'projects')),
    path('groups/',include('usergroups.urls',namespace = 'usergroups')),
    path('admin/', admin.site.urls),
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('',views.ProjectListView.as_view(),name='all'),
    path('new/',views.CreateProjectView.as_view(),name='new'),
    path('<slug:slug>/',views.ProjetDetailView.as_view(),name='single'),
    path('<slug:slug>/delete/',views.ProjectDeleteView.as_view(),name='delete'),
    path('<str:username>',views.UserProjectList.as_view(),name='user_all'),
]

usergroups/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'usergroups'

urlpatterns = [
    path('',views.UsergroupList.as_view(),name='all'),
    path('new/',views.CreateUsergroup.as_view(),name='new'),
    path('projects/in/<slug:slug>/',views.UsergroupDetail.as_view(),name='single'),
    path('join/<slug:slug>/',views.JoinUsergroup.as_view(),name='join'),
    path('leave/<slug:slug>/',views.LeaveUsergroup.as_view(),name='leave'),
]

usergroups/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
from django.contrib.auth.models import User

import misaka
from django.urls import reverse
from django.utils import timezone
from django import template
register = template.Library()

class Usergroup(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True,unique = True)
    description = models.TextField(null = True,default = '')
    description_html = models.TextField(editable=False,null = True,default = '')
    created_at = models.DateTimeField(default=timezone.now())
#    groupadmin = models.ForeignKey(User,related_name='project',on_delete=models.CASCADE)
    users = models.ManyToManyField(User,through='GroupMember')



    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('usergroups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Usergroup,related_name='members',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='members',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


    class Meta:
        unique_together = ['group','user']

usergroups/forms.py
from .models import Usergroup
from django import forms

class UsergroupForm(forms.ModelForm):

    class Meta():
        model=Usergroup
        fields = ('name','description')

usergroups/views.py
from django.shortcuts import render
from django.urls import reverse
from  usergroups.models import Usergroup,GroupMember
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .forms import UsergroupForm
# Create your views here.
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin



class UsergroupList(generic.ListView):
    model = Usergroup
    context_object_name = 'object_list'

class UsergroupDetail(generic.DetailView):
    model = Usergroup

    def check(self):
        #group = get_object_or_404(Usergroup,slug=self.kwargs.get('slug'))
        for oneuser in self.object.users.all():
            if oneuser.username == self.request.user.username:
                return True
        else:
            return False




class CreateUsergroup(LoginRequiredMixin,generic.CreateView):
    login_url = '/login/'
    redirect_field_name = 'usergroups/single.html'
    form_class = UsergroupForm
    model = Usergroup
'''
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.groupadmin = self.request.user
        self.object.save()
        return super().form_valid(form)

'''
class JoinUsergroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('usergroups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Usergroup,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'Already a user')
        else:
            messages.success(self.request,'Successfully joined')

        return super().get(request,*args,**kwargs)

class LeaveUsergroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('usergroups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        try:
            membership = GroupMember.objects.filter(user=self.request.user,group__slug=self.kwargs.get('slug'))
        except:
            messages.warning(self.request,'You are not a member of this group')
        else:
            membership.delete()
            messages.success(self.request,'Successfully left the group')

        return super().get(request,*args,**kwargs)

usergroups/templates/usergroups/usergroup_base.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block post_group %}{% endblock %}

</div>


{% endblock %}

usergroups/templates/usergroups/usergroup_detail.html
{% extends 'usergroups/usergroup_base.html' %}
{% block pregroup %}
<h1>{{ usergroup.name }}</h1>
<h2>Member count:{{ usergroup.members.count }}</h2>

<div >
  {% if view.check %}
  <a href="{% url 'usergroups:leave' slug=usergroup.slug %}" class="btn btn-lg btn-warning "><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
  {% else %}
    <a href="{% url 'usergroups:join' slug=usergroup.slug %}" class="btn btn-lg btn-warning "><span class="glyphicon glyphicon-ok-circle"></span>Join</a>
  {% endif %}

</div>

{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if usergroup.projects.count == 0 %}
  <h1>No projects in this group!</h1>
  {% else %}
  {% for project in usergroup.projects.all %}
  {% include 'projects/_project.html' %}
  {% endfor %}
  {% endif %}

</div>

{% endblock %}

usergroups/templates/usergroups/usergroup_form.html
{% extends 'usergroups/usergroup_base.html' %}
{% load bootstrap3 %}
{% block group_content %}
<h4>Create a group</h4>
 <form  action="{% url 'usergroups:new' %}" method="post" id="groupForm">
   {% csrf_token %}
   {% bootstrap_form form %}
   <input type="submit" class="btn btn-primary btn-large" value="Create">
 </form>
{% endblock %}

usergroups/templates/usergroups/usergroup_list.html
{% extends 'usergroups/usergroup_base.html '%}
{% block pregroup %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h1>Welcome Back</h1>
    <a href="{% url 'projects:user_all' username=user.username %}">@{{ user.username }}</a>
    {% endif %}
    <h1>Groups</h1>
    <h2>Welcome to the Group page</h2>

  </div>

  {% if user.is_authenticated %}
  <a class="btn btn-md btn-fill btn-primary" href="{% url 'usergroups:new' %}"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group</a>
  {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  <div class="list-group">
    {% for group in object_list %}
    <a class="list-group-item" href="{% url 'usergroups:single' slug=group.slug %}"><h3 class="title list-group-item-heading ">{{ group.name }}</h3></a>
    <div class="container-fluid list-group-item-text">
      {{ group.description_html|safe }}
      <div class="row">
        <div class="col-md-4">
            <span class="badge">{{ group.members.count }}</span>
            member{{ group.members.count|pluralize }}
        </div>
        <div class="col-md-4">
            <span class="badge">{{ group.projects.count }}</span>
            project{{ group.projects.count|pluralize }}
        </div>

      </div>
    </div>


    {% endfor%}

  </div>

</div>
{% endblock %}