accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('<int:pk>/profile/',views.UserProfileUpdation.as_view(),name='update_profile'),
    path('<int:pk>/createprofile/',views.NewUserCreation.as_view(),name='create_profile'),
    #path('user_profile_updation/<int:pk>',views.UserProfileUpdation.as_view(),name='update_profile'),
]

blogProject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('',views.HomePage.as_view(),name = 'home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('accouts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('projects/',include('projects.urls',namespace = 'projects')),
    path('groups/',include('usergroups.urls',namespace = 'usergroups')),
    path('admin/', admin.site.urls),
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('',views.ProjectListView.as_view(),name='all'),
    path('new/',views.CreateProjectView.as_view(),name='new'),
    path('<slug:slug>/',views.ProjetDetailView.as_view(),name='single'),
    path('<slug:slug>/delete/',views.ProjectDeleteView.as_view(),name='delete'),
    path('<str:username>',views.UserProjectList.as_view(),name='user_all'),
]

projects/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
from django.contrib.auth.models import User

import misaka
from django.urls import reverse
from django.utils import timezone
from django import template
from usergroups.models import Usergroup
register = template.Library()

class Project(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True,unique = True)
    description = models.TextField(null = True,default = '')
    description_html = models.TextField(editable=False,null = True,default = '')
    created_at = models.DateTimeField(default=timezone.now())
    owner = models.ForeignKey(User,related_name='project',on_delete=models.CASCADE)
    completed_at = models.DateTimeField(blank=True,null=True)
    group = models.ForeignKey(Usergroup,related_name='projects',null=True,blank=True,on_delete=models.CASCADE)



    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('projects:single',kwargs={'slug':self.slug})


class Comment(models.Model):
    author = models.ForeignKey(User,related_name = 'comments',on_delete=models.CASCADE)
    text = models.TextField()
    text_html = models.TextField(editable=False,null = True,default = '')
    project = models.ForeignKey(Project,related_name = 'comments',on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now())

    def get_absolute_url(self):
            return reverse('projects:all')

    def __str__(self):
            return self.text

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.text_html = misaka.html(self.text)
        super().save(*args,**kwargs)

projects/forms.py
from .models import Project,Comment
from django import forms

class ProjectForm(forms.ModelForm):

    class Meta():
        model=Project
        fields = ('name','description','group')



class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('text',)

projects/views.py
from django.shortcuts import render,get_object_or_404
#from django.contrib.auth import redirect_field_name
from django.utils import timezone
from .models import Project,Comment
from .forms import ProjectForm,CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.urls import reverse_lazy,reverse
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
# Create your views here.
class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_all'

    def project_list(self):
        return Project.objects.all()

class ProjetDetailView(DetailView):
    model = Project

    def comments_list(self):
        project = get_object_or_404(Project,pk=self.pk)
        return project.comments.all()

class CreateProjectView(CreateView,LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'projects/single.html'
    form_class = ProjectForm
    model = Project

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

class CreateCommentView(CreateView,LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'projects/single.html'
    form_class = CommentForm
    model = Comment


class ProjectDeleteView(LoginRequiredMixin,SelectRelatedMixin,DeleteView):
    model = Project
    select_related = ('owner')
    success_url = reverse_lazy('projects:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

class UserProjectList(ListView):
    model = Project
    referenced_user = None
    template_name = 'projects/user_project_list.html'
    #def user_project(self):
    def get_queryset(self):
        try:
            self.referenced_user = self.kwargs.get('username')
            #self.post_user = User.objects.prefetch_related('posts').get(username__iexact = self.kwargs.get('username'))
        except :
            raise Http404
        else:
            return Project.objects.filter(owner__username__iexact = self.referenced_user)


    def user_project(self):
        return   Project.objects.filter(owner__username__iexact = self.referenced_user.username)


'''    def delete(self,*args,**kwargs):
        messages.success(self.request,'Project Deleted')
        return super().delete(*args,**kwargs)'''

projects/templates/projects/_comment.html
<div class="comment_view">

  <h4>{{comment.text_html|safe}}</h4>

<div class="media body">
<div class="row">

  <h5>
    <span class="username">
    <a href="{% url 'projects:user_project_list' username=comment.author.username %}">@{{comment.author.username}}</a></span>
    <time class="time">
      {{comment.create_date}}
    </time>
  </h5>
</div>



</div>

</div>

projects/templates/projects/_project.html
<div class="detail_view">
  <h3 class="project_title">{{project.name}}</h3>
  <h4>{{project.description_html|safe}}</h4>

<div class="media body">
<div class="row">

  <h5>
    <span class="username">
    <a href="{% url 'projects:user_all' username=project.owner.username %}">@{{project.owner.username}}</a></span>
    <time class="time">
      <a href="#">{{project.created_at}}</a>
    </time>
  </h5>
</div>



  <div class="media footer">
    {% if user.is_authenticated and project.owner == user %}
      <a href="{% url 'projects:delete' slug=project.slug %}" title='delete' class="btn btn-simple">
<span class="test-danger icon-label">Delete</span>
      </a>
    {% endif %}

  </div>

</div>

</div>

projects/templates/projects/navbar.html
<nav class="navbar navbar-expand-md navbar-light" id="lappy" style="background-color: black;">
<a class="navbar-brand" style="color: white;" href="#">Navbar</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ">
        <li class="nav-item active">
            <a class="nav-link" style="color: white;" href="#"><span><i
                        class="text-white fas fa-home"></i></span>&nbsp;&nbsp;Home <span
                    class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="color: white;" href="#" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span><i class="text-white fas fa-bars"></i></span>&nbsp;&nbsp;My Quiz<span
                    style="visibility: hidden;">---</span>
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Collections</a>
                <a class="dropdown-item" href="#">Favorites</a>
                <a class="dropdown-item" href="#">My Drafts</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" style="color: white;" href="#"><span><i
                        class="text-white fas fa-chart-bar"></i>&nbsp;&nbsp;</span>Reports</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-3">
            <form class="form-inline my-2 my-lg-0">
                <button class="btn  my-2 my-sm-0" type="submit"
                    style="background-color:#d0f224;color:black;box-shadow: 2px 2px grey; font-weight: bold; font-size: 20px;">Create</button>
            </form>
        </li>
        <li class="nav-item dropdown mr-1">
            <a class="nav-link dropdown-toggle" style="color: white;" href="#" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span><i class="text-white fas fa-user-circle" style="font-size: 30px;"></i></span><span
                    style="visibility: hidden;">---</span>&nbsp;&nbsp;
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">View Profile</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" style="color: white;" href="#"><span><i class="text-danger fas fa-sign-out-alt"
                        style="font-size: 25px;"></i>&nbsp;&nbsp;</span>Log out</a>
        </li>
    </ul>
</div>
</nav>
<div class="wrapper" id="mobile">
<!-- Sidebar  -->
<nav id="sidebar">


    <ul class="list-unstyled components">
        <a>
            <p><span><i class="text-white fas fa-home"></i></span>&nbsp;&nbsp;Home
            </p>
        </a>

        <a>
            <p><span><i class="text-white fas fa-compass"></i></span>&nbsp;&nbsp;Discover
            </p>
        </a>

        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><span><i
                        class="text-white fas fa-bars"></i></span>&nbsp;&nbsp;My Quiz</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="#">Collections</a>
                </li>
                <li>
                    <a href="#">Favorites</a>
                </li>
                <li>
                    <a href="#">My drafts</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#"><span><i class="text-white fas fa-chart-bar"></i>&nbsp;&nbsp;</span>Reports</a>
        </li>
        <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                class="dropdown-toggle"><span><i class="fas fa-question-circle"></i>&nbsp;&nbsp;</span>Supports</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                    <a href="#">Help</a>
                </li>
                <li>
                    <a href="#">Blog</a>
                </li>
                <li>
                    <a href="#">Library</a>
                </li>
                <li>
                    <a href="#">Certification</a>
                </li>
                <li>
                    <a href="#">Shop</a>
                </li>
                <li>
                    <a href="#">Suggest a feature</a>
                </li>

            </ul>
        </li>
        <li>
            <a href="#"><span><i class="text-danger fas fa-sign-out-alt"></i></span>&nbsp;&nbsp;Sign out</a>
        </li>
    </ul>

     <div class="help-box" style="border:2px solid #d0f224; padding:5px 5px 5px 5px; margin-left: 10px; margin-right: 10px; margin-top:50px; border-radius:10px ;" >
            <h5 class="text-white m-t-0">For Help ?</h5>
            <p class=""><span class="text-white" style="font-size: 15px;">Email:&nbsp;&nbsp;abc@gmail.com</span> <br /> </p>
        </div>


</nav>

<!-- Page Content  -->
<div id="content">

    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
            </button>



        </div>
    </nav>


</div>
</div>

projects/templates/projects/project_base.html
{% extends 'base.html' %}
{% block body_block %}

<div class="project_page">
  <div class="container">
    <div class="row">
      {% block preproject %} {% endblock %}
      {% block project_content %} {% endblock %}
      {% block post_project %} {% endblock %}
    </div>

  </div>

</div>

{% endblock %}

projects/templates/projects/project_confirm_delete.html
{% extends 'projects/project_base.html' %}

{% block project_content %}

<h3>Are you sure you want to delete this?</h3>
<div class="projects">
  {% include 'projects/_project.html' with project=object hide_delete=True %}
</div>


<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger btn-large" value="Confirm Delete">
  <a href="{% url 'projects:single' username=user.username pk=object.pk %}">Cancel</a>

</form>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'projects/project_base.html' %}

{% block project_content %}
<div class="col-md-8">
  {% include 'projects/_project.html'%}
</div>
{% endblock %}

{% block post_project %}
{% for comment in views.comments_list %}
<div class="jumbotron">
  {% include 'projects/_comment.html'%}
</div>
{% endfor%}
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'projects/project_base.html' %}
{% load bootstrap3 %}
{% block project_content %}
<h4>Create a new Post</h4>
<form id="projectForm" action="{% url 'projects:new' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>

{% endblock %}

projects/templates/projects/project_list.html
{% extends 'projects/project_base.html' %}

{% block preproject %}
<h1>I'm here</h1>
<div class="col-md-4">
  {% if user.is_authenticated %}
  <div class="card card-with-shadow">
    <div class="content">
      <a class="btn btn-primary btn-large" href="{% url 'projects:new' %}"><span class="glyphicon glyphicon-plus-sign">Create</span></a>
<!--     <h1 class="title">Your Groups</h1>
        {% for member_group in get_user_groups %}
        <ul class="list-unstyled">
          <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=member_group.group.slug %}"></a></li>
            {% endfor %}
        </ul>-->

    </div>

  </div>
  {% endif %}
<!--  <div class="card card-with-shadow">
    <div class="content">
      <h1 class="title">Other Groups</h1>
        {% for other_group in get_other_groups %}
        <ul class="list-unstyled">
          <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=member_group.group.slug %}"></a></li>
            {% endfor %}
        </ul>

    </div>

  </div> -->


</div>


<div class="col-md-8">
  {% for project in project_all %}
  {% include 'projects/_project.html' %}
  {% endfor %}
</div>
{% endblock %}

projects/templates/projects/user_project_list.html
{% extends 'projects/project_base.html' %}
{% block project_content %}
<div class="col-md-8">
  <h1>user project</h1>
  {% for project in view.user_project %}
  {% include 'projects/_project.html' %}
  {% endfor %}

</div>
{% endblock %}