accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('<int:pk>/profile/',views.UserProfileUpdation.as_view(),name='update_profile'),
    path('<int:pk>/createprofile/',views.NewUserCreation.as_view(),name='create_profile'),
    #path('user_profile_updation/<int:pk>',views.UserProfileUpdation.as_view(),name='update_profile'),
]

blogProject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('',views.HomePage.as_view(),name = 'home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('accouts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('projects/',include('projects.urls',namespace = 'projects')),
    path('groups/',include('usergroups.urls',namespace = 'usergroups')),
    path('admin/', admin.site.urls),
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('',views.ProjectListView.as_view(),name='all'),
    path('new/',views.CreateProjectView.as_view(),name='new'),
    path('<slug:slug>/',views.ProjetDetailView.as_view(),name='single'),
    path('<slug:slug>/delete/',views.ProjectDeleteView.as_view(),name='delete'),
    path('<str:username>',views.UserProjectList.as_view(),name='user_all'),
]

templates/base.html
<!DOCTYPE html>
<html >
  <head>
    <meta charset="utf-8">
    <title>ProjectBlogs</title>
    <!-- Latest compiled and minified CSS -->
    {% block head_block %}

  {% endblock %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



  </head>
  <body>

      <nav class="navbar mynav" role="navigation" id="navigate">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a  href="{% url 'projects:all' %}">Projects</a></li>
            <li><a  href="{% url 'projects:new' %}">Create Projects</a></li>
            <li><a  href="{% url 'usergroups:all' %}">Group</a></li>
            {% if user.profile %}
            <li><a  href="{% url 'accounts:update_profile' pk=user.pk %}">Profile</a></li>
            {% else %}
            <li><a  href="{% url 'accounts:create_profile' pk=user.pk %}">Create Profile</a></li>
            {% endif %}
            <li><a  href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <li><a  href="{% url 'accounts:login' %}">Login</a></li>
            <li><a  href="{% url 'accounts:signup' %}">Signup</a></li>
             {% endif %}
          </ul>
          </div>
      </nav>
      <div class="container">

        {% block body_block %}

        {% endblock %}

      </div>



  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
 <h1>Welcome to Home Page</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block body_block %}
<h1>You are Logged In!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Thanks for loggin in!</h1>

{% endblock %}